Repository PotterJam/LiveLines, pull requests merged in 2022-02, with the labels that each got.

#18 Allow users to connect to spotify
  LiveLines.Api/Spotify/ISpotifyCredentialsStore.cs
  LiveLines.Api/Spotify/ISpotifyService.cs
  LiveLines.Api/Spotify/SpotifyCredentials.cs
  LiveLines.Spotify/LiveLines.Spotify.csproj
  LiveLines.Spotify/SpotifyController.cs
  LiveLines.Spotify/SpotifyCredentialsStore.cs
  LiveLines.Spotify/SpotifyService.cs
  LiveLines.Users/UserController.cs
  LiveLines.sln
  LiveLines/ClientApp/src/pages/Profile.js
  LiveLines/LiveLines.csproj
  LiveLines/Properties/launchSettings.json
  LiveLines/ServiceModuleExtension.cs
  db.sql
Labels: database changes

#19 Line Privacy and Profiles
  LiveLines.Api/Lines/ILinesService.cs
  LiveLines.Api/Lines/ILinesStore.cs
  LiveLines.Api/Lines/Line.cs
  LiveLines.Api/Lines/LineOperations.cs
  LiveLines.Api/Lines/LinePrivacy.cs
  LiveLines.Api/Lines/LineToCreate.cs
  LiveLines.Api/Users/IProfileStore.cs
  LiveLines.Api/Users/IUserService.cs
  LiveLines.Api/Users/Profile.cs
  LiveLines.Api/Users/ProfileToUpdate.cs
  LiveLines.Extensions/DatabaseExtensions.cs
  LiveLines.Extensions/LiveLines.Extensions.csproj
  LiveLines.Lines/LinesController.cs
  LiveLines.Lines/LinesService.cs
  LiveLines.Lines/LinesStore.cs
  LiveLines.Users/ProfileStore.cs
  LiveLines.Users/ProfileStoreException.cs
  LiveLines.Users/UserController.cs
  LiveLines.Users/UserControllerException.cs
  LiveLines.Users/UserService.cs
  LiveLines/ClientApp/src/components/Enum.js
  LiveLines/ClientApp/src/pages/Profile.js
  LiveLines/Pages/Error.cshtml.cs
  LiveLines/ServiceModuleExtension.cs
  db.sql
Labels: enhancement, database changes

#20 Fix streaks with posting yesterday
  LiveLines.Api/Streaks/IStreakService.cs
  LiveLines.Lines/LinesController.cs
  LiveLines.Streaks/StreakController.cs
  LiveLines.Streaks/StreakService.cs
  LiveLines/ClientApp/src/pages/Home.js
Labels: bug

#22 Only create user when new user, rename last_login to last_update
  LiveLines.Api/Users/IUserService.cs
  LiveLines.Api/Users/IUserStore.cs
  LiveLines.Security/OAuthConfigurer.cs
  LiveLines.Users/UserService.cs
  LiveLines.Users/UserStore.cs
  db.sql
Labels: bug, database changes
